"""operation tracking

Revision ID: 5bf6211f49e5
Revises: 605b7c8fd92d
Create Date: 2026-03-29 18:11:33.224752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf6211f49e5'
down_revision: Union[str, Sequence[str], None] = '605b7c8fd92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('before_state', sa.String(), nullable=True),
    sa.Column('after_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['operation_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table("accounts") as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.now()
            )
        )
        batch_op.add_column(
            sa.Column(
                "deleted_at",
                sa.DateTime(),
                nullable=True
            )
        )
        batch_op.create_unique_constraint('uq_account_iban', ['iban'])
        batch_op.create_unique_constraint('uq_account_name', ['name'])

    with op.batch_alter_table("transactions") as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.now()
            )
        )
        batch_op.add_column(
            sa.Column(
                "deleted_at",
                sa.DateTime(),
                nullable=True
            )
        )

        batch_op.create_unique_constraint('uq_transaction_hash', ['hash'])

    with op.batch_alter_table("debit_categories") as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.now()
            )
        )
        batch_op.add_column(
            sa.Column(
                "deleted_at",
                sa.DateTime(),
                nullable=True
            )
        )
        batch_op.create_unique_constraint('uq_debit_category_category', ['category'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_hash', 'transactions', type_='unique')
    op.drop_column('transactions', 'deleted_at')
    op.drop_column('transactions', 'created_at')
    op.drop_constraint('uq_debit_category_category', 'debit_categories', type_='unique')
    op.drop_column('debit_categories', 'deleted_at')
    op.drop_column('debit_categories', 'created_at')
    op.drop_constraint('uq_account_name', 'accounts', type_='unique')
    op.drop_constraint('uq_account_iban', 'accounts', type_='unique')
    op.drop_column('accounts', 'deleted_at')
    op.drop_column('accounts', 'created_at')
    op.drop_table('operations')
    op.drop_table('operation_groups')
    # ### end Alembic commands ###
