"""fix wrong columns in Operation

Revision ID: 62313518700b
Revises: 5bf6211f49e5
Create Date: 2026-03-29 18:25:49.284017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62313518700b'
down_revision: Union[str, Sequence[str], None] = '5bf6211f49e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('field', sa.String(), nullable=True))
    op.add_column('operations', sa.Column('state', sa.String(), nullable=True))
    op.drop_column('operations', 'after_state')
    op.drop_column('operations', 'before_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('before_state', sa.VARCHAR(), nullable=True))
    op.add_column('operations', sa.Column('after_state', sa.VARCHAR(), nullable=True))
    op.drop_column('operations', 'state')
    op.drop_column('operations', 'field')
    # ### end Alembic commands ###
